version: 2
jobs:
  node:
    working_directory: ~/ReactKata
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: jest tests
          command: |
            mkdir -p test-results/jest
            yarn run test
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml

      - persist_to_workspace:
          root: ~/ReactKata
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

  android:
    working_directory: ~/ReactKata
    docker:
      - image: circleci/android:api-27-node8-alpha

    # use a --login shell so our "set Ruby version" command gets picked up for later steps
    shell: /bin/bash --login -o pipefail

    steps:
      - checkout

      - attach_workspace:
          at: ~/ReactKata

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: detox tests
          command: |
            mkdir -p test-results/jest
            yarn run test:detox:android

      - store_test_results:
          path: android/test-results

      - store_artifacts:
          path: android/test-results

  ios:
    macos:
      xcode: "9.0"
    working_directory: ~/ReactKata

    # use a --login shell so our "set Ruby version" command gets picked up for later steps
    shell: /bin/bash --login -o pipefail

    dependencies:
      cache_directories:
      # Cache the CocoaPods repos to improve build times.
        - ios/Pods

    steps:
      - checkout

      - run:
          name: detox prereqs
          command: |
            brew tap wix/brew
            brew install applesimutils
            yarn run setupdevenv

      - run:
          name: pod install
          command: |
            cd ios
            pod install
            cd ..

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: detox tests
          command: |
            mkdir -p test-results/jest
            yarn run test:detox:ios

      - store_test_results:
          path: ios/test-results

      - store_artifacts:
          path: ios/test-results

workflows:
  version: 2
  node-android-ios:
    jobs:
      - node
      - android:
          requires:
            - node
      - ios:
          requires:
            - node
